FROM mhoush/py3

COPY requirements_dev.txt /requirements_dev.txt
COPY . /usr/src/app

RUN apk add --update make && \
    pip install -r requirements_dev.txt && \
    pip install /usr/src/app && \
    rm -rf /var/tmp/* /root/.cache/* /var/cahce/apk/* /tmp/*

ENV TERM=xterm-256color

VOLUME /usr/src/app

WORKDIR /usr/src/app

CMD ["make", "test"]
